"""12121

Revision ID: 31072030c4e8
Revises: 77003faedca5
Create Date: 2025-02-20 17:34:14.732679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31072030c4e8'
down_revision: Union[str, None] = '77003faedca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_user_id_key', 'students', type_='unique')
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'user_id')
    op.drop_constraint('teachers_user_id_key', 'teachers', type_='unique')
    op.drop_constraint('teachers_user_id_fkey', 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teachers_user_id_fkey', 'teachers', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('teachers_user_id_key', 'teachers', ['user_id'])
    op.add_column('students', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('students_user_id_key', 'students', ['user_id'])
    # ### end Alembic commands ###
