"""no teacher student

Revision ID: ee4252824336
Revises: f0745e889093
Create Date: 2025-02-20 20:10:13.252313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4252824336'
down_revision: Union[str, None] = 'f0745e889093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
