"""12121

Revision ID: f67ac4a1f519
Revises: 97d9f8a328fa
Create Date: 2025-02-20 17:44:59.065358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67ac4a1f519'
down_revision: Union[str, None] = '97d9f8a328fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.add_column('teachers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'teachers', ['user_id'])
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'user_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###
