version: '3.7'
services:
  db:
    image: postgres:16
    container_name: blog_db
    volumes:
      - ./config.yaml:/src/app/config/config.yaml
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=google_disk
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 3

  posts:
    image: google_image
    build:
      context: .
    container_name: google_disk
    volumes:
      - ./config.yaml:/src/app/config/config.yaml
    command: /bin/bash -c "alembic upgrade head && gunicorn src.app.asgi:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"
    depends_on:
      - db
      - redis

  celery:
    image: celery_image
    build:
      context: .
    container_name: celery_name
    command: celery --app=src.app.tasks.celery:celery worker -l INFO
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7
    container_name: blog_redis
    ports:
      - 6379:6379
